import { Poppins } from "next/font/google";
import "./globals.css";
import ClientProvider from "./ClientProvider";
const poppins = Poppins({ 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata = {
  icons: {
    icon: "/favicon.ico",
  },
  title: "Razco Foods",
  description: "Generated by Razco Foods",
};

export default function RootLayout({ children }) {
  // const DynamicLogin = dynamic(()=> import("@/Modal/LoginModal"),{ssr: false,loading: ()=> <p>Loading...</p>})
  // const RegisterModal = dynamic(()=> import("@/Modal/RegisterModal"),{ssr: false,loading: ()=> <p>Loading...</p>})

  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <ClientProvider>
          <div className="custom-class">{children}</div>
        </ClientProvider>
      </body>
    </html>
  );
}
